# Generated by Django 3.2.21 on 2023-11-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='main.country'),
            preserve_default=False,
        ),
    ]
