# Generated by Django 3.2.21 on 2023-11-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_studio',
        ),
        migrations.DeleteModel(
            name='MovieStudio',
        ),
    ]
