# Generated by Django 3.2.21 on 2023-11-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_country'),
        ('main', '0004_alter_movie_release_time'),
    ]

    operations = [
    ]
